return {
  -- 'ibhagwan/fzf-lua',
  -- dependencies = {
  --   { 'nvim-tree/nvim-web-devicons', enabled = vim.g.have_nerd_font },
  --   { 'folke/trouble.nvim', optional = true },
  -- },
  -- -- event = 'VeryLazy',
  -- config = function()
  --   local fzf = require 'fzf-lua'
  --   local config = fzf.config
  --   local actions = fzf.actions
  --
  --   local opts = {
  --     keymap = {
  --       builtin = {
  --         ['<C-f>'] = 'preview-page-down',
  --         ['<C-b>'] = 'preview-page-up',
  --         ['<C-p>'] = 'toggle-preview',
  --       },
  --       fzf = {
  --         ['ctrl-f'] = 'preview-page-down',
  --         ['ctrl-b'] = 'preview-page-up',
  --         ['ctrl-p'] = 'toggle-preview',
  --       },
  --     },
  --     files = {
  --       cwd_prompt = false,
  --       actions = {
  --         ['enter'] = actions.file_edit,
  --         ['alt-i'] = actions.toggle_ignore,
  --         ['alt-h'] = actions.toggle_hidden,
  --       },
  --     },
  --     grep = {
  --       actions = {
  --         ['alt-i'] = { actions.toggle_ignore },
  --         ['alt-h'] = { actions.toggle_hidden },
  --       },
  --     },
  --     winopts = {
  --       height = 0.60,
  --       width = 0.60,
  --       row = 0.5,
  --       col = 0.5,
  --       preview = {
  --         scrollchars = { '┃', '' },
  --         hidden = false,
  --       },
  --     },
  --     fzf_opts = {
  --       ['--no-scrollbar'] = true,
  --       -- ['--layout'] = 'default',
  --     },
  --     lsp = {
  --       -- code_actions = {
  --       --   -- previewer = vim.fn.executable 'delta' == 1 and 'codeaction_native' or nil,
  --       --   layout = 'vertical',
  --       --   preview = {
  --       --     layout = 'vertical',
  --       --     vertical = 'down:15,border-top',
  --       --     hidden = 'false',
  --       --     -- title = ' Code Action Preview ',
  --       --     -- title_pos = 'center',
  --       --   },
  --       -- },
  --     },
  --     -- ui_select = function(fzf_opts, items)
  --     --   local current_opts = vim.deepcopy(fzf_opts or {})
  --     --   if current_opts.kind == 'codeaction' then
  --     --     local codeaction_winopts = {
  --     --       layout = 'vertical',
  --     --       width = 0.5,
  --     --       height = math.floor(math.min(vim.o.lines * 0.8 - 16, #items + 2) + 0.5) + 16,
  --     --       preview = {
  --     --         layout = 'vertical',
  --     --         vertical = 'down:15,border-top',
  --     --         hidden = 'false',
  --     --         -- title = ' Code Action Preview ',
  --     --         -- title_pos = 'center',
  --     --       },
  --     --       title = ' Code Actions ',
  --     --       title_pos = 'center',
  --     --     }
  --     --     current_opts.winopts = vim.tbl_deep_extend('force', current_opts.winopts or {}, codeaction_winopts)
  --     --     current_opts.prompt = current_opts.prompt or 'Code Action > '
  --     --   end
  --     --   return current_opts
  --     -- end,
  --   }
  --
  --   fzf.setup(opts)
  --   fzf.register_ui_select()
  --
  --   -- fzf.register_ui_select(opts.ui_select)
  --
  --   if pcall(require, 'trouble.sources.fzf') then
  --     fzf.config.defaults.actions.files['ctrl-t'] = require('trouble.sources.fzf').actions.open
  --   end
  --
  --   vim.keymap.set('n', '<leader>sh', fzf.help_tags, { desc = '[S]earch [H]elp (fzf)' })
  --   vim.keymap.set('n', '<leader>sk', fzf.keymaps, { desc = '[S]earch [K]eymaps (fzf)' })
  --   vim.keymap.set('n', '<leader>sf', fzf.files, { desc = '[S]earch [F]iles (fzf)' })
  --   vim.keymap.set('n', '<leader>ss', fzf.builtin, { desc = '[S]earch [S]elect fzf action' }) -- Shows fzf-lua built-ins
  --   vim.keymap.set('n', '<leader>sw', fzf.grep_cword, { desc = '[S]earch current [W]ord (fzf)' })
  --   vim.keymap.set('n', '<leader>sg', fzf.live_grep, { desc = '[S]earch by [G]rep (fzf)' })
  --   vim.keymap.set('n', '<leader>sd', fzf.diagnostics_document, { desc = '[S]earch [D]iagnostics Document (fzf)' })
  --   vim.keymap.set('n', '<leader>sD', fzf.diagnostics_workspace, { desc = '[S]earch [D]iagnostics Workspace (fzf)' })
  --   vim.keymap.set('n', '<leader>sr', fzf.resume, { desc = '[S]earch [R]esume (fzf)' })
  --   vim.keymap.set('n', '<leader>s.', fzf.oldfiles, { desc = '[S]earch Recent Files ("." for repeat) (fzf)' })
  --   vim.keymap.set('n', '<leader><leader>', fzf.buffers, { desc = '[ ] Find existing buffers (fzf)' })
  --
  --   -- Fuzzy search in current buffer (blines is often preferred over current_buffer_fuzzy_find)
  --   vim.keymap.set('n', '<leader>/', fzf.blines, { desc = '[/] Fuzzily search in current buffer lines (fzf)' })
  --   -- If you prefer the file content search:
  --   -- vim.keymap.set('n', '<leader>/', fzf.current_buffer_fuzzy_find, { desc = '[/] Fuzzily search in current buffer content (fzf)' })
  --
  --   -- Grep in open files
  --   vim.keymap.set('n', '<leader>s/', function()
  --     fzf.live_grep {
  --       grep_open_files = true,
  --       -- You might need to configure fzf-lua's grep command or ensure 'rg' is available
  --       -- prompt = 'Live Grep Open Files> ' -- Customize prompt if desired
  --     }
  --   end, { desc = '[S]earch [/] in Open Files (fzf)' })
  --
  --   vim.keymap.set('n', '<leader>sn', function()
  --     fzf.files { cwd = vim.fn.stdpath 'config' }
  --   end, { desc = '[S]earch [N]eovim files (fzf)' })
  -- end,
}
